# Generated by Django 4.0.1 on 2023-03-29 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gene_created_transcript_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='sequence',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Sequence must only contain A, T, G, or C.', regex='^[ATGC]*$')]),
        ),
    ]
