# Generated by Django 4.0.1 on 2023-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gene_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='sequence',
            field=models.TextField(),
        ),
    ]
